# Generated by Django 5.2.8 on 2025-11-16 02:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorEditedImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Editor Edited Image Asset',
                'verbose_name_plural': 'Editor Edited Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorOriginalImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Editor Original Image Asset',
                'verbose_name_plural': 'Editor Original Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorEditedImageAssetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('edited_image_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edited_image_asset_file', to='editor.editoreditedimageasset')),
            ],
            options={
                'verbose_name': 'Editor Edited Image Asset File',
                'verbose_name_plural': 'Editor Edited Image Asset Files',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='editoreditedimageasset',
            name='original_image_asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edited_image_asset', to='editor.editororiginalimageasset'),
        ),
        migrations.CreateModel(
            name='EditorOriginalImageAssetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('original_image_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_image_asset_file', to='editor.editororiginalimageasset')),
            ],
            options={
                'verbose_name': 'Editor Original Image Asset File',
                'verbose_name_plural': 'Editor Original Image Asset Files',
                'abstract': False,
            },
        ),
    ]
