"""
This type stub file was generated by pyright.
"""

from django.utils.functional import cached_property

class Settings:
    """
    This is a simple class to take the place of the global settings object. An
    instance will contain all of our settings as attributes, with default values
    if they are not specified by the configuration.
    """
    @cached_property
    def defaults(self):  # -> dict[str, Any]:
        ...
    def __getattr__(self, name):  # -> Any:
        ...

settings = ...
