"""
This type stub file was generated by pyright.
"""

def write_qrcode_image(data, out):  # -> None:
    """Write a QR code image for data to out.

    The written image is in image/svg+xml format.

    One of `qrcode` or `segno` are required. If neither is found, raises
    ModuleNotFoundError.
    """
    ...
