[tool.poetry]
name = "webpeditor"
version = "0.1.0"
description = "Web application for editing WebP images"
authors = ["timok19 <tima1199@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
astroid = "^3.1.0"
dill = "^0.3.7"
isort = "^5.13.2"
lazy-object-proxy = "^1.10.0"
tomlkit = "^0.12.1"
platformdirs = "^4.2.0"
asgiref = "*"
django-appconf = "*"
django-compressor = "^4.4"
djangorestframework = "*"
dnspython = "*"
mccabe = "*"
pip = "*"
pycodestyle = "*"
pytz = "*"
rcssmin = "1.1.1"
rjsmin = "*"
setuptools = "*"
sqlparse = "^0.4.4"
toml = "*"
tomli = "*"
typing-extensions = "*"
wheel = "*"
wrapt = "*"
django-cors-headers = "*"
pymongo = "^4.5.0"
django-environ = "*"
django-extensions = "*"
requests = "==2.31.0"
cython = "*"
ipython = "*"
python-jose = {extras = ["cryptography"], version = "*"}
django-imagekit = "*"
opencv-python = "*"
gunicorn = "*"
whitenoise = "*"
python-dotenv = "*"
cloudinary = "^1.33.0"
raven = "*"
django = "4.2.10"
redis = "^5.0.0"
py-spy = "*"
pillow = "*"
mongoengine = "*"
django-jsonfield = "*"
deptry = "*"
cryptography = "^42.0.5"
certifi = "^2024.2.2"
reactpy-django = "*"
channels = {version = "*", extras = ["daphne"]}
twisted = {version = "*", extras = ["http2", "tls"]}
black = "^24.2.0"
beanie = "^1.21.0"
django-asgi-lifespan = "^0.2.0"
pydantic = "1.10.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
