[tool.poetry]
name = "webpeditor"
version = "0.1.0"
description = "Web application for editing WebP images"
authors = ["timok19 <tima1199@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
astroid = "^2.15.6"
dill = "^0.3.7"
isort = "==5.12.0"
lazy-object-proxy = "==1.9.0"
tomlkit = "^0.12.1"
platformdirs = "^3.10.0"
asgiref = "*"
django-appconf = "*"
django-compressor = "*"
djangorestframework = "*"
dnspython = "*"
mccabe = "*"
pip = "*"
pycodestyle = "*"
pytz = "*"
rcssmin = "*"
rjsmin = "*"
setuptools = "*"
sqlparse = "*"
toml = "*"
tomli = "*"
typing-extensions = "*"
wheel = "*"
wrapt = "*"
django-cors-headers = "*"
pymongo = "3.12.3"
django-environ = "*"
django-extensions = "*"
requests = "==2.31.0"
cython = "*"
ipython = "*"
python-jose = {extras = ["cryptography"], version = "*"}
django-imagekit = "*"
opencv-python = "*"
gunicorn = "*"
whitenoise = "*"
python-dotenv = "*"
cloudinary = "^1.33.0"
raven = "*"
django = "==4.1.10"
redis = "^4.6.0"
py-spy = "*"
pillow = "*"
mongoengine = "*"
django-jsonfield = "*"
deptry = "*"
cryptography = "==41.0.3"
certifi = "==2023.7.22"
reactpy-django = "*"
channels = {version = "*", extras = ["daphne"]}
twisted = {version = "*", extras = ["http2", "tls"]}
black = "^23.7.0"
beanie = "^1.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
