disable_logging = true

interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    ".",
]

[[modules ]]
path = "webpeditor.settings"
depends_on = ["webpeditor_app.apps"]

[[modules ]]
path = "webpeditor_app.infrastructure"
depends_on = ["webpeditor.settings", "webpeditor_app.domain", "webpeditor_app.core", "webpeditor_app.common"]

[[modules ]]
path = "webpeditor_app.api"
depends_on = ["webpeditor_app.domain", "webpeditor_app.core", "webpeditor_app.application", "webpeditor_app.infrastructure", "webpeditor_app.common"]

[[modules ]]
path = "webpeditor_app.apps"
depends_on = []

[[modules ]]
path = "webpeditor_app.types"
depends_on = []

[[modules ]]
path = "webpeditor"
depends_on = []

[[modules ]]
path = "webpeditor_app"
depends_on = []

[[modules ]]
path = "webpeditor.urls"
depends_on = ["webpeditor_app"]

[[modules ]]
path = "webpeditor.asgi"
depends_on = []

[[modules ]]
path = "webpeditor_app.common"
depends_on = ["webpeditor_app.core", "webpeditor.settings", "webpeditor_app.domain", "webpeditor_app.types"]

[[modules ]]
path = "webpeditor_app.core"
depends_on = ["webpeditor.settings"]

[[modules ]]
path = "webpeditor_app.application"
depends_on = ["webpeditor.settings", "webpeditor_app.types", "webpeditor_app.common", "webpeditor_app.core", "webpeditor_app.infrastructure", "webpeditor_app.domain"]

[[modules ]]
path = "webpeditor_app.admin"
depends_on = ["webpeditor_app.types", "webpeditor_app.infrastructure"]

[[modules ]]
path = "webpeditor_app.domain"
depends_on = []

[[modules ]]
path = "webpeditor_app.urls"
depends_on = ["webpeditor_app.api", "webpeditor_app", "webpeditor.settings"]

[[modules ]]
path = "manage"
depends_on = []

[[modules ]]
path = "webpeditor_app.middlewares"
depends_on = ["webpeditor_app.core", "webpeditor_app.api"]
