"""
This type stub file was generated by pyright.
"""

EXCEPTION_CODES = ...

class Response(dict):
    def __init__(self, result, response, **kwargs) -> None: ...

def execute_request(http_connector, method, params, headers, auth, api_url, **options):  # -> Response:
    ...
