# Generated by Django 4.1.5 on 2023-02-02 01:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('original_image', models.BinaryField()),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='EditedImage',
            fields=[
                ('edited_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type_edited', models.CharField(max_length=255)),
                ('edited_image', models.BinaryField()),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpeditor_app.originalimage')),
            ],
        ),
    ]
