# Generated by Django 4.1.5 on 2023-02-03 17:44

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import webpeditor_app.services.validators.image_size_validator


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('original_image', models.ImageField(upload_to='media/',
                                                     validators=[django.core.validators.MaxLengthValidator(6291456),
                                                                 webpeditor_app.services.validators.image_size_validator.validate_image_file_size])),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EditedImage',
            fields=[
                ('edited_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type_edited', models.CharField(max_length=255)),
                ('edited_image', models.ImageField(upload_to='media/',
                                                   validators=[django.core.validators.MaxLengthValidator(6291456),
                                                               webpeditor_app.services.validators.image_size_validator.validate_image_file_size])),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_image',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpeditor_app.originalimage')),
            ],
        ),
    ]
