# Generated by Django 4.1.5 on 2023-02-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image',
            field=models.ImageField(max_length=6291456, upload_to=None),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_image',
            field=models.ImageField(max_length=6291456, upload_to=None),
        ),
    ]
