# Generated by Django 4.1.7 on 2023-04-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0002_convertedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convertedimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Converted Image', 'verbose_name_plural': 'Converted Images'},
        ),
    ]
