# Generated by Django 4.1.5 on 2023-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0002_alter_editedimage_edited_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editedimage',
            name='edited_image',
        ),
        migrations.RemoveField(
            model_name='originalimage',
            name='original_image',
        ),
        migrations.AddField(
            model_name='editedimage',
            name='edited_image_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='original_image_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
