# Generated by Django 4.1.5 on 2023-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0003_remove_editedimage_edited_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_path',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='editedimage',
            name='session_id',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_image_path',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='session_id',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
