# Generated by Django 4.1.5 on 2023-02-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0004_alter_editedimage_edited_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalimage',
            name='original_image_path',
        ),
        migrations.AddField(
            model_name='originalimage',
            name='original_image',
            field=models.ImageField(default=None, max_length=6000000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_path',
            field=models.ImageField(default=None, max_length=6000000, upload_to=''),
        ),
    ]
