# Generated by Django 4.1.5 on 2023-02-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0005_remove_originalimage_original_image_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='edited_image_path',
            new_name='edited_image_url',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='original_image',
            new_name='original_image_url',
        ),
    ]
