# Generated by Django 4.1.5 on 2023-02-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0008_alter_editedimage_edited_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editedimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='originalimage',
            name='updated_at',
        ),
    ]
