# Generated by Django 4.1.5 on 2023-02-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0009_remove_editedimage_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_url',
            field=models.ImageField(default=None, max_length=6291456, upload_to=''),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_image_url',
            field=models.ImageField(default=None, max_length=6291456, upload_to=''),
        ),
    ]
