# Generated by Django 4.1.5 on 2023-02-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0010_alter_editedimage_edited_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalimage',
            old_name='file_name',
            new_name='image_file',
        ),
    ]
