# Generated by Django 4.1.5 on 2023-02-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0011_rename_file_name_originalimage_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='original_image',
            new_name='original_image_file',
        ),
    ]
