# Generated by Django 4.1.5 on 2023-02-12 15:15

from django.db import migrations, models
import webpeditor_app.services.validators.image_file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0013_alter_originalimage_original_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_url',
            field=models.ImageField(default=None, upload_to='', validators=[webpeditor_app.services.validators.image_file_validator.validate_image_file_size]),
        ),
    ]
