# Generated by Django 4.1.5 on 2023-02-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0014_alter_editedimage_edited_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedimage',
            name='session_id_expiration_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='session_id_expiration_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='editedimage',
            name='session_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='session_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
