# Generated by Django 4.1.5 on 2023-02-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0014_alter_editedimage_edited_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='session_id',
            new_name='user_token',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='session_id',
            new_name='user_token',
        ),
    ]
