# Generated by Django 4.1.5 on 2023-02-14 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0015_editedimage_session_id_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='session_id_expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='session_id_expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
