# Generated by Django 4.1.5 on 2023-02-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0016_alter_editedimage_session_id_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='session_id',
            new_name='user_folder_name',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='session_id',
            new_name='user_folder_name',
        ),
    ]
