# Generated by Django 4.1.5 on 2023-02-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0017_rename_session_id_editedimage_user_folder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='user_folder_name',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='user_folder_name',
            new_name='user_id',
        ),
    ]
