# Generated by Django 4.1.5 on 2023-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0020_editedimage_edited_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_file',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001C7C1E02A70>', max_length=255),
        ),
    ]
