# Generated by Django 4.1.5 on 2023-02-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0023_alter_editedimage_current_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_file',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000193F215EAD0>', max_length=255),
        ),
    ]
