# Generated by Django 4.1.5 on 2023-02-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0025_alter_editedimage_edited_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_file',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000020CC8E6B6A0>', max_length=255),
        ),
    ]
