# Generated by Django 4.1.5 on 2023-02-25 23:31

import cropperjs.models
from django.db import migrations
import webpeditor_app.services.validators.image_file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0028_alter_editedimage_edited_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_url',
            field=cropperjs.models.CropperImageField(default=None, upload_to='edited/', validators=[webpeditor_app.services.validators.image_file_validator.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_image_url',
            field=cropperjs.models.CropperImageField(default=None, upload_to='', validators=[webpeditor_app.services.validators.image_file_validator.validate_image_file_size]),
        ),
    ]
