# Generated by Django 4.1.5 on 2023-03-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0029_alter_editedimage_edited_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedimage',
            name='session_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='session_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
