# Generated by Django 4.1.7 on 2023-03-15 20:56

import cropperjs.models
from django.db import migrations, models
import webpeditor_app.services.validators.image_size_validator


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0030_editedimage_session_id_originalimage_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='edited_image_file',
            new_name='edited_image_name',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='image_file',
            new_name='image_name',
        ),
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_url',
            field=cropperjs.models.CropperImageField(blank=True, null=True, upload_to='edited/', validators=[webpeditor_app.services.validators.image_size_validator.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='editedimage',
            name='user_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_image_url',
            field=cropperjs.models.CropperImageField(blank=True, null=True, upload_to='', validators=[webpeditor_app.services.validators.image_size_validator.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='user_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
