# Generated by Django 4.1.7 on 2023-03-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0031_rename_edited_image_file_editedimage_edited_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
    ]
