# Generated by Django 4.1.7 on 2023-03-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0032_alter_editedimage_current_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editedimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Edited Image', 'verbose_name_plural': 'Edited Images'},
        ),
        migrations.AlterModelOptions(
            name='originalimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Original Image', 'verbose_name_plural': 'Original Images'},
        ),
    ]
