# Generated by Django 4.1.7 on 2023-03-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0033_alter_editedimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedimage',
            name='is_currently_editing',
            field=models.BooleanField(default=True),
        ),
    ]
