# Generated by Django 4.1.7 on 2023-03-16 01:53

import cropperjs.models
from django.db import migrations
import webpeditor_app.services.validators.image_size_validator


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0034_editedimage_is_currently_editing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_url',
            field=cropperjs.models.CropperImageField(blank=True, null=True, upload_to='', validators=[webpeditor_app.services.validators.image_size_validator.validate_image_file_size]),
        ),
    ]
