# Generated by Django 4.1.7 on 2023-03-17 01:09

from django.db import migrations, models
import webpeditor_app.services.validators.image_file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0035_alter_editedimage_edited_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[webpeditor_app.services.validators.image_file_validator.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[webpeditor_app.services.validators.image_file_validator.validate_image_file_size]),
        ),
    ]
