# Generated by Django 4.1.7 on 2023-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0036_alter_editedimage_edited_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='edited_image_url',
            new_name='edited_image',
        ),
        migrations.RenameField(
            model_name='editedimage',
            old_name='original_image_file',
            new_name='original_image',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='original_image_url',
            new_name='original_image',
        ),
        migrations.RemoveField(
            model_name='editedimage',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='editedimage',
            name='is_currently_editing',
        ),
        migrations.RemoveField(
            model_name='editedimage',
            name='steps',
        ),
    ]
