# Generated by Django 4.1.7 on 2023-04-24 20:05

from django.db import migrations, models
import webpeditor_app.services.validators.image_file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0037_rename_edited_image_url_editedimage_edited_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedimage',
            name='edited_image',
            field=models.ImageField(blank=True, null=True, upload_to='edited_image/', validators=[webpeditor_app.services.validators.image_file_validator.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='original_image/', validators=[webpeditor_app.services.validators.image_file_validator.validate_image_file_size]),
        ),
    ]
