# Generated by Django 4.1.7 on 2023-04-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0038_alter_editedimage_edited_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='content_type_edited',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='editedimage',
            old_name='edited_image_id',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='editedimage',
            old_name='edited_image_name',
            new_name='image_name',
        ),
        migrations.RemoveField(
            model_name='editedimage',
            name='edited_image',
        ),
        migrations.RemoveField(
            model_name='originalimage',
            name='original_image',
        ),
        migrations.AddField(
            model_name='editedimage',
            name='image_url',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='originalimage',
            name='image_url',
            field=models.CharField(default='', max_length=350),
        ),
    ]
