# Generated by Django 4.1.7 on 2023-04-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0039_rename_content_type_edited_editedimage_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedimage',
            old_name='session_id',
            new_name='session_key',
        ),
        migrations.RenameField(
            model_name='editedimage',
            old_name='session_id_expiration_date',
            new_name='session_key_expiration_date',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='session_id',
            new_name='session_key',
        ),
        migrations.RenameField(
            model_name='originalimage',
            old_name='session_id_expiration_date',
            new_name='session_key_expiration_date',
        ),
    ]
