# Generated by Django 5.2.8 on 2025-11-26 19:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='ConverterImageAssetDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Converter Image Asset',
                'verbose_name_plural': 'Converter Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorEditedImageAssetDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Editor Edited Image Asset',
                'verbose_name_plural': 'Editor Edited Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorOriginalImageAssetDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Editor Original Image Asset',
                'verbose_name_plural': 'Editor Original Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConverterConvertedImageAssetFileDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('image_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_image_asset_files', to='infrastructure.converterimageassetdo')),
            ],
            options={
                'verbose_name': 'Converter Converted Image Asset File',
                'verbose_name_plural': 'Converter Converted Image Asset Files',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConverterOriginalImageAssetFileDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('image_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_image_asset_files', to='infrastructure.converterimageassetdo')),
            ],
            options={
                'verbose_name': 'Converter Original Image Asset File',
                'verbose_name_plural': 'Converter Original Image Asset Files',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorEditedImageAssetFileDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('edited_image_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edited_image_asset_file', to='infrastructure.editoreditedimageassetdo')),
            ],
            options={
                'verbose_name': 'Editor Edited Image Asset File',
                'verbose_name_plural': 'Editor Edited Image Asset Files',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='editoreditedimageassetdo',
            name='original_image_asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edited_image_asset', to='infrastructure.editororiginalimageassetdo'),
        ),
        migrations.CreateModel(
            name='EditorOriginalImageAssetFileDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('original_image_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_image_asset_file', to='infrastructure.editororiginalimageassetdo')),
            ],
            options={
                'verbose_name': 'Editor Original Image Asset File',
                'verbose_name_plural': 'Editor Original Image Asset Files',
                'abstract': False,
            },
        ),
    ]
