# Generated by Django 4.1.7 on 2023-04-29 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OriginalImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=255)),
                ("image_url", models.CharField(default="", max_length=350)),
                ("user_id", models.CharField(max_length=32, null=True)),
                ("session_key", models.CharField(max_length=120, null=True)),
                ("session_key_expiration_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Original Image",
                "verbose_name_plural": "Original Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EditedImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_name", models.CharField(default="", max_length=255)),
                ("content_type", models.CharField(max_length=255)),
                ("image_url", models.CharField(default="", max_length=350)),
                ("user_id", models.CharField(max_length=32, null=True)),
                ("session_key", models.CharField(max_length=120, null=True)),
                ("session_key_expiration_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("original_image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="webpeditor_app.originalimage")),
            ],
            options={
                "verbose_name": "Edited Image",
                "verbose_name_plural": "Edited Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
