# Generated by Django 5.2 on 2025-04-04 17:10

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import webpeditor_app.models.converter
import webpeditor_app.models.editor
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=120, null=True)),
                ('session_key_expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConverterImageAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_converted_image_asset', to='webpeditor_app.appuser')),
            ],
            options={
                'verbose_name': 'Converted Image Asset',
                'verbose_name_plural': 'Converted Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConverterConvertedImageAssetFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('file', models.ImageField(blank=True, max_length=1024, upload_to=webpeditor_app.models.converter.upload_to_folder)),
                ('image_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_image_asset_files', to='webpeditor_app.converterimageasset')),
            ],
            options={
                'verbose_name': 'Converted Image Asset File',
                'verbose_name_plural': 'Converted Image Asset Files',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConverterOriginalImageAssetFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('file', models.ImageField(blank=True, max_length=1024, upload_to=webpeditor_app.models.converter.upload_to_folder)),
                ('image_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_image_asset_files', to='webpeditor_app.converterimageasset')),
            ],
            options={
                'verbose_name': 'Original Image Asset File',
                'verbose_name_plural': 'Original Image Asset Files',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorEditedImageAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_edited_image_asset', to='webpeditor_app.appuser')),
            ],
            options={
                'verbose_name': 'Edited Image Asset',
                'verbose_name_plural': 'Edited Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorEditedImageAssetFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('file', models.ImageField(blank=True, max_length=1024, upload_to=webpeditor_app.models.editor.upload_to_folder)),
                ('edited_image_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edited_image_asset_file', to='webpeditor_app.editoreditedimageasset')),
            ],
            options={
                'verbose_name': 'Edited Image Asset File',
                'verbose_name_plural': 'Edited Image Asset Files',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditorOriginalImageAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_original_image_asset', to='webpeditor_app.appuser')),
            ],
            options={
                'verbose_name': 'Original Image Asset',
                'verbose_name_plural': 'Original Image Assets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='editoreditedimageasset',
            name='original_image_asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edited_image_asset', to='webpeditor_app.editororiginalimageasset'),
        ),
        migrations.CreateModel(
            name='EditorOriginalImageAssetFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('filename_shorter', models.CharField(blank=True, max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('format_description', models.CharField(blank=True, max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('aspect_ratio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('color_mode', models.CharField(max_length=10)),
                ('exif_data', models.JSONField()),
                ('image_file', models.ImageField(blank=True, max_length=1024, upload_to=webpeditor_app.models.editor.upload_to_folder)),
                ('original_image_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_image_asset_file', to='webpeditor_app.editororiginalimageasset')),
            ],
            options={
                'verbose_name': 'Original Image Asset File',
                'verbose_name_plural': 'Original Image Asset Files',
                'abstract': False,
            },
        ),
    ]
