# Generated by Django 5.2.6 on 2025-09-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterimageasset',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='editoreditedimageasset',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='editororiginalimageasset',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
