# Generated by Django 4.1.7 on 2023-04-30 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConvertedImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=32, null=True)),
                ("image_set", models.JSONField()),
                ("session_key", models.CharField(max_length=120, null=True)),
                ("session_key_expiration_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
