# Generated by Django 5.2.1 on 2025-05-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editororiginalimageassetfile',
            old_name='image_file',
            new_name='file',
        ),
    ]
