# Generated by Django 5.1.5 on 2025-02-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0002_converterconvertedimageassetfile_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converterconvertedimageassetfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='converteroriginalimageassetfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='editoreditedimageassetfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='editororiginalimageassetfile',
            name='file_size',
        ),
        migrations.AddField(
            model_name='converterconvertedimageassetfile',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='converterconvertedimageassetfile',
            name='format_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='converterconvertedimageassetfile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='converterconvertedimageassetfile',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='converterconvertedimageassetfile',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='converteroriginalimageassetfile',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='converteroriginalimageassetfile',
            name='format_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='converteroriginalimageassetfile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='converteroriginalimageassetfile',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='converteroriginalimageassetfile',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='editoreditedimageassetfile',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='editoreditedimageassetfile',
            name='format_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='editoreditedimageassetfile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='editoreditedimageassetfile',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='editoreditedimageassetfile',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='editororiginalimageassetfile',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='editororiginalimageassetfile',
            name='format_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='editororiginalimageassetfile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='editororiginalimageassetfile',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='editororiginalimageassetfile',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
