# Generated by Django 5.2.3 on 2025-06-22 17:23

from django.db import migrations, models

from webpeditor_app.infrastructure.database.utils import generate_id


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0002_alter_converterconvertedimageassetfile_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="id",
            field=models.CharField(default=generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
