# Generated by Django 5.1.2 on 2024-10-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0003_alter_convertedimage_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="editedimage",
            old_name="image_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="originalimage",
            old_name="image_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="convertedimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
