# Generated by Django 5.2.3 on 2025-06-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0003_alter_appuser_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='converterconvertedimageassetfile',
            options={'verbose_name': 'Converter Converted Image Asset File', 'verbose_name_plural': 'Converter Converted Image Asset Files'},
        ),
        migrations.AlterModelOptions(
            name='converterimageasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Converter Image Asset', 'verbose_name_plural': 'Converter Image Assets'},
        ),
        migrations.AlterModelOptions(
            name='converteroriginalimageassetfile',
            options={'verbose_name': 'Converter Original Image Asset File', 'verbose_name_plural': 'Converter Original Image Asset Files'},
        ),
        migrations.AlterModelOptions(
            name='editoreditedimageasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Editor Edited Image Asset', 'verbose_name_plural': 'Editor Edited Image Assets'},
        ),
        migrations.AlterModelOptions(
            name='editoreditedimageassetfile',
            options={'verbose_name': 'Editor Edited Image Asset File', 'verbose_name_plural': 'Editor Edited Image Asset Files'},
        ),
        migrations.AlterModelOptions(
            name='editororiginalimageasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Editor Original Image Asset', 'verbose_name_plural': 'Editor Original Image Assets'},
        ),
        migrations.AlterModelOptions(
            name='editororiginalimageassetfile',
            options={'verbose_name': 'Editor Original Image Asset File', 'verbose_name_plural': 'Editor Original Image Asset Files'},
        ),
    ]
