# Generated by Django 5.1.2 on 2024-10-30 16:01

import cloudinary.models
import webpeditor_app.validators.model_validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0004_rename_image_id_editedimage_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convertedimage",
            name="image_set",
        ),
        migrations.AddField(
            model_name="convertedimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                null=True,
                validators=[webpeditor_app.validators.model_validators.ConvertedImageValidator.validate_file_size],
                verbose_name="converted",
            ),
        ),
    ]
