# Generated by Django 5.1.2 on 2024-10-31 09:30

import cloudinary.models
import webpeditor_app.validators.model_validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0005_remove_convertedimage_image_set_convertedimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, validators=[webpeditor_app.validators.model_validators.ConvertedImageValidator.validate_file_size]
            ),
        ),
    ]
