# Generated by Django 5.1.5 on 2025-07-08 13:31

import webpeditor_app.infrastructure.database.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0005_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.CharField(default=webpeditor_app.infrastructure.database.utils.generate_id, editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='session_key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
