# Generated by Django 5.2.4 on 2025-07-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpeditor_app', '0006_alter_appuser_id_alter_appuser_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
    ]
