# Generated by Django 5.1.2 on 2024-10-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0006_alter_convertedimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convertedimage",
            name="image",
        ),
        migrations.AddField(
            model_name="convertedimage",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
