# Generated by Django 5.1.2 on 2024-10-31 23:51

import webpeditor_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0007_remove_convertedimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedimage",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=webpeditor_app.models.upload_to_folder),
        ),
    ]
