# Generated by Django 5.1.2 on 2024-11-02 00:41

import django.db.models.deletion
import webpeditor_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0008_alter_convertedimage_image_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convertedimage",
            name="image_file",
        ),
        migrations.CreateModel(
            name="ConvertedImageFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_file", models.ImageField(blank=True, max_length=1024, upload_to=webpeditor_app.models.upload_to_folder)),
                (
                    "converted_image",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="image_files", to="webpeditor_app.convertedimage"),
                ),
            ],
        ),
    ]
