# Generated by Django 5.1.2 on 2024-11-02 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0010_alter_convertedimagefile_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConvertedImage",
            new_name="ConvertedImageAsset",
        ),
        migrations.RenameModel(
            old_name="ConvertedImageFile",
            new_name="ConvertedImageAssetFile",
        ),
        migrations.RenameModel(
            old_name="EditedImage",
            new_name="EditedImageAsset",
        ),
        migrations.RenameModel(
            old_name="OriginalImage",
            new_name="OriginalImageAsset",
        ),
        migrations.AlterModelOptions(
            name="convertedimageasset",
            options={"ordering": ["-created_at"], "verbose_name": "Converted Image Asset", "verbose_name_plural": "Converted Image Assets"},
        ),
        migrations.AlterModelOptions(
            name="convertedimageassetfile",
            options={"verbose_name": "Converted Image Asset File", "verbose_name_plural": "Converted Image Asset Files"},
        ),
        migrations.AlterModelOptions(
            name="editedimageasset",
            options={"ordering": ["-created_at"], "verbose_name": "Edited Image Asset", "verbose_name_plural": "Edited Image Assets"},
        ),
        migrations.AlterModelOptions(
            name="originalimageasset",
            options={"ordering": ["-created_at"], "verbose_name": "Original Image Asset", "verbose_name_plural": "Original Image Assets"},
        ),
        migrations.RenameField(
            model_name="convertedimageassetfile",
            old_name="converted_image",
            new_name="converted_image_asset",
        ),
        migrations.RenameField(
            model_name="editedimageasset",
            old_name="original_image",
            new_name="original_image_asset",
        ),
    ]
