# Generated by Django 5.1.2 on 2024-11-03 14:47

import django.db.models.deletion
import webpeditor_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpeditor_app", "0011_rename_convertedimage_convertedimageasset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editedimageasset",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="originalimageasset",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="editedimageasset",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="editedimageasset",
            name="original_image_asset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="edited_image_asset", to="webpeditor_app.originalimageasset"
            ),
        ),
        migrations.CreateModel(
            name="EditedImageAssetFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_file", models.ImageField(blank=True, max_length=1024, upload_to=webpeditor_app.models.upload_to_folder)),
                (
                    "edited_image_asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image_file", to="webpeditor_app.editedimageasset"
                    ),
                ),
            ],
            options={
                "verbose_name": "Edited Image Asset File",
                "verbose_name_plural": "Edited Image Asset Files",
            },
        ),
        migrations.CreateModel(
            name="OriginalImageAssetFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_file", models.ImageField(blank=True, max_length=1024, upload_to=webpeditor_app.models.upload_to_folder)),
                (
                    "original_image_asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image_file", to="webpeditor_app.originalimageasset"
                    ),
                ),
            ],
            options={
                "verbose_name": "Original Image Asset File",
                "verbose_name_plural": "Original Image Asset Files",
            },
        ),
    ]
