"""
This type stub file was generated by pyright.
"""

import logging
from typing import Dict, Tuple, Type

from .base import BaseCache
from .decorators import cached, cached_stampede, multi_cached
from .factory import Cache, caches

__version__ = ...
logger: logging.Logger = ...
AIOCACHE_CACHES: Dict[str, Type[BaseCache]] = ...
__all__: Tuple[str, ...] = ("caches", "Cache", "cached", "cached_stampede", "multi_cached")
