"""
This type stub file was generated by pyright.
"""

from django import forms

def cl_init_js_callbacks(form, request): # -> None:
    ...

class CloudinaryInput(forms.TextInput):
    input_type = ...
    def render(self, name, value, attrs=..., renderer=...): # -> SafeText:
        ...



class CloudinaryJsFileField(forms.Field):
    default_error_messages = ...
    def __init__(self, attrs=..., options=..., autosave=..., *args, **kwargs) -> None:
        ...

    def enable_callback(self, request): # -> None:
        ...

    def to_python(self, value): # -> CloudinaryResource | None:
        """Convert to CloudinaryResource"""
        ...

    def validate(self, value): # -> None:
        """Validate the signature"""
        ...



class CloudinaryUnsignedJsFileField(CloudinaryJsFileField):
    def __init__(self, upload_preset, attrs=..., options=..., autosave=..., *args, **kwargs) -> None:
        ...



class CloudinaryFileField(forms.FileField):
    my_default_error_messages = ...
    default_error_messages = ...
    def __init__(self, options=..., autosave=..., *args, **kwargs) -> None:
        ...

    def to_python(self, value): # -> Any | None:
        """Upload and convert to CloudinaryResource"""
        ...
