"""
Django settings for webpeditor project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
import environ

# Environment variables instance
env = environ.Env()
environ.Env().read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Local development
# SECRET_KEY = env('SECRET_KEY')

# Production
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app', '*']

# Application definition
# In development mode. Delete this in production mode (add domains in white list)
INSTALLED_APPS = [
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'rest_framework',
    'corsheaders',
    'cropperjs',
    'imagekit',
    'webpeditor_app.apps.WebpeditorAppConfig',
]

# Delete in production
CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8000',
    'http://127.0.0.1:8000',
)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webpeditor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webpeditor.wsgi.application'

MAX_IMAGE_FILE_SIZE = 6_000_000

MAX_SIZE_OF_IMAGE_FILES = 50_000_000

DATA_UPLOAD_MAX_NUMBER_FILES = 20

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

FILE_UPLOAD_MAX_MEMORY_SIZE = 10_485_760

DATA_UPLOAD_MAX_MEMORY_SIZE = 52_428_800

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Local development
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'CLIENT': {
#             # Add local env variables to store host string
#             'host': f'mongodb+srv://{env("DATABASE_USER")}:{env("DATABASE_PASSWORD")}{env("HOST_LINK")}/?retryWrites'
#                     '=true&w=majority',
#             'name': env("DATABASE_NAME"),
#             'authMechanism': 'SCRAM-SHA-1'  # For atlas cloud db
#         },
#     }
# }

# Production
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'CLIENT': {
            # Add local env variables to store host string
            'host': f'mongodb+srv://'
                    f'{os.environ.get("DATABASE_USER")}:{os.environ.get("DATABASE_PASSWORD")}'
                    f'{os.environ.get("HOST_LINK")}/?retryWrites=true&w=majority',
            'name': os.environ.get("DATABASE_NAME"),
            'authMechanism': 'SCRAM-SHA-1'  # For atlas cloud db
        },
    }
}

# Path for future migrations
MIGRATION_MODULES = {
    'webpeditor_app': 'webpeditor_app.models.database.migrations'
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Session handling

SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_SAMESITE = 'Strict'

CSRF_COOKIE_SAMESITE = 'Strict'

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = True

# PROD ONLY
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'static' / 'media' / 'uploaded_images'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Compressor settings
COMPRESS_ROOT = BASE_DIR / 'static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

# Static files directory
STATICFILES_DIRS = [BASE_DIR / 'static']

# Allow slash in url paths
APPEND_SLASH = False
