"""
This type stub file was generated by pyright.
"""

import logging
import msgpack
from .serializers import BaseSerializer, JsonSerializer, NullSerializer, PickleSerializer, StringSerializer

logger = ...
__all__ = ["BaseSerializer", "NullSerializer", "StringSerializer", "PickleSerializer", "JsonSerializer", "MsgPackSerializer"]
